
spring:
  profiles:
    active: nonprod
server:
  port: 8082
---

spring:
  profiles:
    active:
      on-active: local
  kafka:
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

---

spring:
  profiles:
    active:
      on-active: nonprod
  kafka:
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:9094,localhost:9095,localhost:9096
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
      ssl:
        trust-store-location: file:/C:/SSL/client.truststore.jks
        trust-store-password: Kafka@123
        key-store-password: Kafka@123
        key-store-location: file:/C:/SSL/client.keystore.jks
    producer:
      bootstrap-servers: localhost:9094,localhost:9095,localhost:9096
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security:
          protocol: SSL
          ssl.endpoint.identification.algorithm:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

---

spring:
  profiles:
    active:
      on-active: prod
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group